/*
 * generated by Xtext 2.9.1
 */
package de.roma.cocktail.xtext.ui;

import com.google.inject.Injector;
import de.roma.cocktail.xtext.lpp.ui.internal.LppActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LppExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LppActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LppActivator.getInstance().getInjector(LppActivator.DE_ROMA_COCKTAIL_XTEXT_LPP);
	}
	
}
