/*
 * generated by Xtext 2.9.1
 */
package de.roma.cocktail.xtext.parser.antlr;

import com.google.inject.Inject;
import de.roma.cocktail.xtext.parser.antlr.internal.InternalLppParser;
import de.roma.cocktail.xtext.services.LppGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LppParser extends AbstractAntlrParser {

	@Inject
	private LppGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLppParser createParser(XtextTokenStream stream) {
		return new InternalLppParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ParserModel";
	}

	public LppGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LppGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
