/**
 * generated by Xtext 2.9.2
 */
package de.roma.cocktail.xtext.rpp;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.roma.cocktail.xtext.rpp.SingleRule#getStart <em>Start</em>}</li>
 *   <li>{@link de.roma.cocktail.xtext.rpp.SingleRule#getRule <em>Rule</em>}</li>
 *   <li>{@link de.roma.cocktail.xtext.rpp.SingleRule#getContent <em>Content</em>}</li>
 * </ul>
 *
 * @see de.roma.cocktail.xtext.rpp.RppPackage#getSingleRule()
 * @model
 * @generated
 */
public interface SingleRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Start</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' containment reference.
   * @see #setStart(RuleStart)
   * @see de.roma.cocktail.xtext.rpp.RppPackage#getSingleRule_Start()
   * @model containment="true"
   * @generated
   */
  RuleStart getStart();

  /**
   * Sets the value of the '{@link de.roma.cocktail.xtext.rpp.SingleRule#getStart <em>Start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' containment reference.
   * @see #getStart()
   * @generated
   */
  void setStart(RuleStart value);

  /**
   * Returns the value of the '<em><b>Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rule</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule</em>' containment reference.
   * @see #setRule(RuleDefinition)
   * @see de.roma.cocktail.xtext.rpp.RppPackage#getSingleRule_Rule()
   * @model containment="true"
   * @generated
   */
  RuleDefinition getRule();

  /**
   * Sets the value of the '{@link de.roma.cocktail.xtext.rpp.SingleRule#getRule <em>Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rule</em>' containment reference.
   * @see #getRule()
   * @generated
   */
  void setRule(RuleDefinition value);

  /**
   * Returns the value of the '<em><b>Content</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Content</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' containment reference.
   * @see #setContent(CodeBlock)
   * @see de.roma.cocktail.xtext.rpp.RppPackage#getSingleRule_Content()
   * @model containment="true"
   * @generated
   */
  CodeBlock getContent();

  /**
   * Sets the value of the '{@link de.roma.cocktail.xtext.rpp.SingleRule#getContent <em>Content</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content</em>' containment reference.
   * @see #getContent()
   * @generated
   */
  void setContent(CodeBlock value);

} // SingleRule
