/**
 * generated by Xtext 2.9.1
 */
package de.roma.cocktail.xtext.lpp;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Precedence Row</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.roma.cocktail.xtext.lpp.PrecedenceRow#getType <em>Type</em>}</li>
 *   <li>{@link de.roma.cocktail.xtext.lpp.PrecedenceRow#getTokens <em>Tokens</em>}</li>
 * </ul>
 *
 * @see de.roma.cocktail.xtext.lpp.LppPackage#getPrecedenceRow()
 * @model
 * @generated
 */
public interface PrecedenceRow extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link de.roma.cocktail.xtext.lpp.PrecedenceType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see de.roma.cocktail.xtext.lpp.PrecedenceType
   * @see #setType(PrecedenceType)
   * @see de.roma.cocktail.xtext.lpp.LppPackage#getPrecedenceRow_Type()
   * @model
   * @generated
   */
  PrecedenceType getType();

  /**
   * Sets the value of the '{@link de.roma.cocktail.xtext.lpp.PrecedenceRow#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see de.roma.cocktail.xtext.lpp.PrecedenceType
   * @see #getType()
   * @generated
   */
  void setType(PrecedenceType value);

  /**
   * Returns the value of the '<em><b>Tokens</b></em>' reference list.
   * The list contents are of type {@link de.roma.cocktail.xtext.lpp.DefinedToken}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tokens</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tokens</em>' reference list.
   * @see de.roma.cocktail.xtext.lpp.LppPackage#getPrecedenceRow_Tokens()
   * @model
   * @generated
   */
  EList<DefinedToken> getTokens();

} // PrecedenceRow
