/**
 * generated by Xtext 2.9.1
 */
package de.roma.cocktail.xtext;

import de.roma.cocktail.xtext.ParserStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ParserStandaloneSetup extends ParserStandaloneSetupGenerated {
  public static void doSetup() {
    ParserStandaloneSetup _parserStandaloneSetup = new ParserStandaloneSetup();
    _parserStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
