/**
 * generated by Xtext 2.9.1
 */
package de.roma.cocktail.xtext;

import com.google.inject.Binder;
import de.roma.cocktail.xtext.AbstractParserRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ParserRuntimeModule extends AbstractParserRuntimeModule {
  @Override
  public void configure(final Binder binder) {
    super.configure(binder);
  }
}
