/**
 * generated by Xtext 2.9.1
 */
package de.roma.cocktail.xtext.parser;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Grammer Rules</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link de.roma.cocktail.xtext.parser.GrammerRules#getRules <em>Rules</em>}</li>
 * </ul>
 * </p>
 *
 * @see de.roma.cocktail.xtext.parser.ParserPackage#getGrammerRules()
 * @model
 * @generated
 */
public interface GrammerRules extends EObject
{
  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link de.roma.cocktail.xtext.parser.GrammarRule}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rules</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see de.roma.cocktail.xtext.parser.ParserPackage#getGrammerRules_Rules()
   * @model containment="true"
   * @generated
   */
  EList<GrammarRule> getRules();

} // GrammerRules
