/**
 * generated by Xtext 2.9.1
 */
package de.roma.cocktail.xtext.ast;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Target Code Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.roma.cocktail.xtext.ast.TargetCodeExpression#getCode <em>Code</em>}</li>
 * </ul>
 *
 * @see de.roma.cocktail.xtext.ast.AstPackage#getTargetCodeExpression()
 * @model
 * @generated
 */
public interface TargetCodeExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Code</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Code</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code</em>' attribute list.
   * @see de.roma.cocktail.xtext.ast.AstPackage#getTargetCodeExpression_Code()
   * @model unique="false"
   * @generated
   */
  EList<String> getCode();

} // TargetCodeExpression
