/*
 * generated by Xtext
 */
package org.xtext.cocktail.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.cocktail.ui.internal.ScannerActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ScannerExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ScannerActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ScannerActivator.getInstance().getInjector(ScannerActivator.ORG_XTEXT_COCKTAIL_SCANNER);
	}
	
}
